services:
#    oc_symfony_platform.example:
#        class: OCSymfony\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    oc_symfony_platform.antispam:
        class: OCSymfony\PlatformBundle\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - 50
        calls:
            - [setLocale, [%locale%]]

    oc_symfony_platform.twig.antispam_extension:
        class: OCSymfony\PlatformBundle\Twig\AntispamExtension
        arguments:
            - "@oc_symfony_platform.antispam"
        tags:
            - { name: twig.extension }

    oc_symfony_platform.email.application_mailer:
        class: OCSymfony\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    oc_symfony_platform.doctrine_listener.application_creation:
        class: OCSymfony\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@oc_symfony_platform.email.application_mailer"
        tag:
            - { name: doctrine.event_listener, event: postPersist }

    oc_symfony_platform.purge.advert:
        class: OCSymfony\PlatformBundle\Purge\OCPurge
        arguments:
            - "@doctrine.orm.entity_manager"

    oc_symfony_platform.validator.antiflood:
        class: OCSymfony\PlatformBundle\Validator\AntiFlood
        arguments:
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: oc_symfony_platform_antiflood }

    oc_symfony_platform.form.ckeditor:
        class: OCSymfony\PlatformBundle\Form\CkeditorType
        class:
            - { name: form.type, alias: ckeditor }

    oc_symfony_platform.beta.html_adder:
            class: OCSymfony\PlatformBundle\Beta\BetaHTMLAdder

    oc_symfony_platform.beta.listener:
        class: OCSymfony\PlatformBundle\Beta\BetaListener
        arguments:
            - "@oc_symfony_platform.beta.html_adder"
            - "2017-08-15"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }

