services:
#    oc_symfony_platform.example:
#        class: OCSymfony\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    oc_symfony_platform.antispam:
        class: OCSymfony\PlatformBundle\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50

    oc_symfony_platform.email.application_mailer:
        class: OCSymfony\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    oc_symfony_platform.doctrine_listener.application_creation:
            class: OCSymfony\PlatformBundle\DoctrineListener\ApplicationCreationListener
            arguments:
                - "@oc_symfony_platform.email.application_mailer"
            tag:
                - { name: doctrine.event_listener, event: postPersist }

    oc_symfony_platform.purge.advert:
            class: OCSymfony\PlatformBundle\Purge\OCPurge
            arguments:
                - "@doctrine.orm.entity_manager"