oc_symfony_core:
    resource: "@OCSymfonyCoreBundle/Resources/config/routing.yml"
    prefix:   /

oc_symfony_platform:
    resource: "@OCSymfonyPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

app:
    resource: '@AppBundle/Controller/'
    type: annotation
