services:
#    oc_symfony_platform.example:
#        class: OCSymfony\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    oc_platform.antispam:
        class: OCSymfony\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50