oc_symfony_core_homepage:
    path:     /
    defaults: { _controller: OCSymfonyCoreBundle:Core:index }

oc_symfony_core_contact:
    path:     /contact
    defaults: { _controller: OCSymfonyCoreBundle:Core:contact }

oc_symfony_core_forum:
    path:     /forum
    defaults: { _controller: OCSymfonyCoreBundle:Core:forum }

